version: '2'

services:

  dms:
    image: andrglo/everest:16.13.0
    hostname: json-schema-table
    command: tail -f /dev/null
    working_dir: /root/json-schema-table
    volumes:
      - ./docker_fish_history:/root/.config/fish/fish_history
      - .:/root/json-schema-table
    environment:
      - NODE_ENV=test
      - MSSQL_PASSWORD=Passw0rd
      - MSSQL_HOST=mssql
      - POSTGRES_HOST=postgres
    restart: always

  mssql:
    image: mcr.microsoft.com/mssql/server:2019-CU11-ubuntu-20.04
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Passw0rd
    restart: always

  postgres:
    image: postgres:12.2-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: always
