version: '2'

services:

  postgres:
    image: postgres
    ports:
      - 5432:5432
    restart: always
  mssql:
    image: microsoft/mssql-server-linux
    ports:
      - 1433:1433
    environment:
      ACCEPT_EULA: "y"
      SA_PASSWORD: "Passw0rd"
